from django.core.management.base import BaseCommand

from core.models import SkillAssessmentQuestion


QUESTIONS = [
    {
        'skill': 'web_development',
        'level': 'beginner',
        'prompt': 'What does responsive web design mainly ensure?',
        'choices': [
            {'key': 'A', 'text': 'The website only works on desktop screens'},
            {'key': 'B', 'text': 'The website adapts cleanly to different screen sizes'},
            {'key': 'C', 'text': 'The website has no images'},
            {'key': 'D', 'text': 'The website uses only one color'},
        ],
        'correct_choice': 'B',
        'explanation': 'Responsive design adapts layout and content to different devices.',
    },
    {
        'skill': 'web_development',
        'level': 'beginner',
        'prompt': 'Which HTTP method is normally used to create a new record through an API?',
        'choices': [
            {'key': 'A', 'text': 'GET'},
            {'key': 'B', 'text': 'POST'},
            {'key': 'C', 'text': 'TRACE'},
            {'key': 'D', 'text': 'OPTIONS'},
        ],
        'correct_choice': 'B',
        'explanation': 'POST is commonly used for create operations.',
    },
    {
        'skill': 'web_development',
        'level': 'beginner',
        'prompt': 'What is the main role of CSS?',
        'choices': [
            {'key': 'A', 'text': 'Storing database rows'},
            {'key': 'B', 'text': 'Styling and laying out web pages'},
            {'key': 'C', 'text': 'Encrypting passwords'},
            {'key': 'D', 'text': 'Sending email only'},
        ],
        'correct_choice': 'B',
        'explanation': 'CSS controls presentation: layout, spacing, colors, typography, and responsive behavior.',
    },
    {
        'skill': 'web_development',
        'level': 'beginner',
        'prompt': 'A form should not submit empty required fields. Where should validation happen?',
        'choices': [
            {'key': 'A', 'text': 'Only in the browser'},
            {'key': 'B', 'text': 'Only in the database backup'},
            {'key': 'C', 'text': 'In both frontend UX and backend rules'},
            {'key': 'D', 'text': 'Nowhere'},
        ],
        'correct_choice': 'C',
        'explanation': 'Frontend validation improves UX, while backend validation protects the system.',
    },
    {
        'skill': 'web_development',
        'level': 'beginner',
        'prompt': 'What does a 404 response usually mean?',
        'choices': [
            {'key': 'A', 'text': 'The requested resource was not found'},
            {'key': 'B', 'text': 'The request succeeded'},
            {'key': 'C', 'text': 'The server is on fire'},
            {'key': 'D', 'text': 'The password is too short'},
        ],
        'correct_choice': 'A',
        'explanation': 'HTTP 404 means the server could not find the requested resource.',
    },
    {
        'skill': 'web_development',
        'level': 'intermediate',
        'prompt': 'A dashboard becomes slow after rendering 5,000 rows. What is the best first UI fix?',
        'choices': [
            {'key': 'A', 'text': 'Add more gradients'},
            {'key': 'B', 'text': 'Paginate or virtualize the list'},
            {'key': 'C', 'text': 'Remove authentication'},
            {'key': 'D', 'text': 'Use larger images'},
        ],
        'correct_choice': 'B',
        'explanation': 'Pagination or virtualization reduces DOM work and improves perceived speed.',
    },
    {
        'skill': 'web_development',
        'level': 'intermediate',
        'prompt': 'Why should API secrets not be stored in frontend React code?',
        'choices': [
            {'key': 'A', 'text': 'React cannot display strings'},
            {'key': 'B', 'text': 'Frontend bundles are visible to users'},
            {'key': 'C', 'text': 'Secrets make buttons bigger'},
            {'key': 'D', 'text': 'Browsers reject all API calls'},
        ],
        'correct_choice': 'B',
        'explanation': 'Frontend code is shipped to the browser, so secrets can be inspected.',
    },
    {
        'skill': 'web_development',
        'level': 'intermediate',
        'prompt': 'What is idempotency useful for in payment-related endpoints?',
        'choices': [
            {'key': 'A', 'text': 'Preventing duplicate effects from retries'},
            {'key': 'B', 'text': 'Changing the app color'},
            {'key': 'C', 'text': 'Making passwords visible'},
            {'key': 'D', 'text': 'Skipping all validation'},
        ],
        'correct_choice': 'A',
        'explanation': 'Idempotency helps retries avoid double charges or duplicate state changes.',
    },
    {
        'skill': 'web_development',
        'level': 'intermediate',
        'prompt': 'Which database relationship best fits one contract having many deliverables?',
        'choices': [
            {'key': 'A', 'text': 'Foreign key from deliverable to contract'},
            {'key': 'B', 'text': 'One-to-one only'},
            {'key': 'C', 'text': 'No relationship'},
            {'key': 'D', 'text': 'Store all deliverables in the email field'},
        ],
        'correct_choice': 'A',
        'explanation': 'A foreign key allows many deliverables to link to one contract.',
    },
    {
        'skill': 'web_development',
        'level': 'intermediate',
        'prompt': 'What should happen if backend validation fails on form submission?',
        'choices': [
            {'key': 'A', 'text': 'Show useful field or error feedback to the user'},
            {'key': 'B', 'text': 'Pretend it succeeded'},
            {'key': 'C', 'text': 'Delete unrelated data'},
            {'key': 'D', 'text': 'Reload forever'},
        ],
        'correct_choice': 'A',
        'explanation': 'Good apps surface actionable validation feedback.',
    },
    {
        'skill': 'web_development',
        'level': 'advanced',
        'prompt': 'In a distributed payment workflow, why are provider webhooks often treated as source-of-truth updates?',
        'choices': [
            {'key': 'A', 'text': 'They confirm asynchronous state from the payment provider'},
            {'key': 'B', 'text': 'They are prettier than UI buttons'},
            {'key': 'C', 'text': 'They replace all authentication'},
            {'key': 'D', 'text': 'They are always sent by the browser'},
        ],
        'correct_choice': 'A',
        'explanation': 'Webhooks confirm external payment events that happen after the initial request.',
    },
    {
        'skill': 'web_development',
        'level': 'advanced',
        'prompt': 'What is a safe way to evolve a working payment flow when adding milestones?',
        'choices': [
            {'key': 'A', 'text': 'Replace all payment code immediately'},
            {'key': 'B', 'text': 'Add a schedule layer first and keep the proven payment rail intact'},
            {'key': 'C', 'text': 'Remove database migrations'},
            {'key': 'D', 'text': 'Let users edit signed contracts freely'},
        ],
        'correct_choice': 'B',
        'explanation': 'A non-invasive schedule layer lowers risk while preserving working payments.',
    },
    {
        'skill': 'web_development',
        'level': 'advanced',
        'prompt': 'Why should long-running or external operations usually not hold a database transaction open?',
        'choices': [
            {'key': 'A', 'text': 'It can lock rows too long and reduce reliability'},
            {'key': 'B', 'text': 'It makes CSS invalid'},
            {'key': 'C', 'text': 'It prevents JSON from existing'},
            {'key': 'D', 'text': 'It removes all indexes'},
        ],
        'correct_choice': 'A',
        'explanation': 'Holding transactions during slow external calls can cause lock contention and failure cascades.',
    },
    {
        'skill': 'web_development',
        'level': 'advanced',
        'prompt': 'What is the purpose of a unique constraint on an assessment answer per attempt and question?',
        'choices': [
            {'key': 'A', 'text': 'Preventing duplicate answers for the same question'},
            {'key': 'B', 'text': 'Allowing infinite duplicate scoring'},
            {'key': 'C', 'text': 'Changing the user avatar'},
            {'key': 'D', 'text': 'Disabling timestamps'},
        ],
        'correct_choice': 'A',
        'explanation': 'The constraint protects scoring from duplicate submissions.',
    },
    {
        'skill': 'web_development',
        'level': 'advanced',
        'prompt': 'A public API endpoint changes money state. Which combination is safest?',
        'choices': [
            {'key': 'A', 'text': 'Authentication, authorization, validation, idempotency, and provider confirmation'},
            {'key': 'B', 'text': 'No auth and trust the client'},
            {'key': 'C', 'text': 'Only console logs'},
            {'key': 'D', 'text': 'CSS animations only'},
        ],
        'correct_choice': 'A',
        'explanation': 'Payment state needs layered protections.',
    },
    {
        'skill': 'design',
        'level': 'beginner',
        'prompt': 'What does visual hierarchy help users do?',
        'choices': [
            {'key': 'A', 'text': 'Understand what matters first'},
            {'key': 'B', 'text': 'Forget the page purpose'},
            {'key': 'C', 'text': 'Make every element identical'},
            {'key': 'D', 'text': 'Remove all labels'},
        ],
        'correct_choice': 'A',
        'explanation': 'Hierarchy guides attention through size, weight, spacing, and contrast.',
    },
    {
        'skill': 'design',
        'level': 'beginner',
        'prompt': 'Why is enough color contrast important?',
        'choices': [
            {'key': 'A', 'text': 'It improves readability and accessibility'},
            {'key': 'B', 'text': 'It hides important text'},
            {'key': 'C', 'text': 'It replaces content strategy'},
            {'key': 'D', 'text': 'It makes loading slower'},
        ],
        'correct_choice': 'A',
        'explanation': 'Contrast helps more users read and interact comfortably.',
    },
    {
        'skill': 'design',
        'level': 'beginner',
        'prompt': 'What is whitespace used for in interface design?',
        'choices': [
            {'key': 'A', 'text': 'Separating and organizing content'},
            {'key': 'B', 'text': 'Wasting the whole screen'},
            {'key': 'C', 'text': 'Breaking buttons'},
            {'key': 'D', 'text': 'Replacing navigation'},
        ],
        'correct_choice': 'A',
        'explanation': 'Whitespace improves grouping, scanning, and comfort.',
    },
    {
        'skill': 'design',
        'level': 'beginner',
        'prompt': 'A button should usually look clickable because of its:',
        'choices': [
            {'key': 'A', 'text': 'Affordance'},
            {'key': 'B', 'text': 'Database table'},
            {'key': 'C', 'text': 'Server hostname'},
            {'key': 'D', 'text': 'File extension only'},
        ],
        'correct_choice': 'A',
        'explanation': 'Affordance tells users what an element can do.',
    },
    {
        'skill': 'design',
        'level': 'beginner',
        'prompt': 'Why should similar actions use consistent styling?',
        'choices': [
            {'key': 'A', 'text': 'Users learn patterns faster'},
            {'key': 'B', 'text': 'It makes every page random'},
            {'key': 'C', 'text': 'It prevents saving data'},
            {'key': 'D', 'text': 'It removes accessibility'},
        ],
        'correct_choice': 'A',
        'explanation': 'Consistency lowers cognitive load.',
    },
    {
        'skill': 'design',
        'level': 'intermediate',
        'prompt': 'A dashboard for repeated operational work should usually prioritize:',
        'choices': [
            {'key': 'A', 'text': 'Dense but organized information and predictable controls'},
            {'key': 'B', 'text': 'Only a huge marketing hero'},
            {'key': 'C', 'text': 'Hidden navigation'},
            {'key': 'D', 'text': 'Unreadable decoration'},
        ],
        'correct_choice': 'A',
        'explanation': 'Operational tools should be efficient for scanning and repeated action.',
    },
    {
        'skill': 'design',
        'level': 'intermediate',
        'prompt': 'What is the best way to handle a long transaction list in a dashboard panel?',
        'choices': [
            {'key': 'A', 'text': 'Let it stretch the whole page forever'},
            {'key': 'B', 'text': 'Put it in a bounded internal scroll area'},
            {'key': 'C', 'text': 'Hide all transactions permanently'},
            {'key': 'D', 'text': 'Make text overlap'},
        ],
        'correct_choice': 'B',
        'explanation': 'Bounded scroll preserves layout while keeping access to all rows.',
    },
    {
        'skill': 'design',
        'level': 'intermediate',
        'prompt': 'Why should form labels remain clear and close to inputs?',
        'choices': [
            {'key': 'A', 'text': 'They reduce user mistakes'},
            {'key': 'B', 'text': 'They make validation impossible'},
            {'key': 'C', 'text': 'They replace the submit button'},
            {'key': 'D', 'text': 'They slow the database'},
        ],
        'correct_choice': 'A',
        'explanation': 'Clear labels help users understand what each field needs.',
    },
    {
        'skill': 'design',
        'level': 'intermediate',
        'prompt': 'A design system primarily helps teams maintain:',
        'choices': [
            {'key': 'A', 'text': 'Consistency and reusable patterns'},
            {'key': 'B', 'text': 'Random styles'},
            {'key': 'C', 'text': 'Only backend logs'},
            {'key': 'D', 'text': 'Broken spacing'},
        ],
        'correct_choice': 'A',
        'explanation': 'Design systems create shared patterns and reduce drift.',
    },
    {
        'skill': 'design',
        'level': 'intermediate',
        'prompt': 'What is a good empty state supposed to do?',
        'choices': [
            {'key': 'A', 'text': 'Explain what is missing and guide the next action'},
            {'key': 'B', 'text': 'Confuse users'},
            {'key': 'C', 'text': 'Show unrelated code'},
            {'key': 'D', 'text': 'Remove the page heading'},
        ],
        'correct_choice': 'A',
        'explanation': 'Empty states should orient and help users proceed.',
    },
    {
        'skill': 'design',
        'level': 'advanced',
        'prompt': 'In a high-trust fintech-like interface, which design choice is strongest?',
        'choices': [
            {'key': 'A', 'text': 'Clear status, restrained styling, and visible audit information'},
            {'key': 'B', 'text': 'Ambiguous payment states'},
            {'key': 'C', 'text': 'Hidden amounts'},
            {'key': 'D', 'text': 'No confirmation feedback'},
        ],
        'correct_choice': 'A',
        'explanation': 'Trust-sensitive workflows need clarity, restraint, and transparent status.',
    },
    {
        'skill': 'design',
        'level': 'advanced',
        'prompt': 'Why is progressive disclosure useful in complex workflows?',
        'choices': [
            {'key': 'A', 'text': 'It reveals complexity only when needed'},
            {'key': 'B', 'text': 'It removes all choices'},
            {'key': 'C', 'text': 'It forces all details onto one screen'},
            {'key': 'D', 'text': 'It breaks navigation'},
        ],
        'correct_choice': 'A',
        'explanation': 'Progressive disclosure reduces overload while keeping advanced options accessible.',
    },
    {
        'skill': 'design',
        'level': 'advanced',
        'prompt': 'When designing a modal or panel with variable content, what prevents layout damage?',
        'choices': [
            {'key': 'A', 'text': 'Defined max heights, internal scrolling, and stable spacing'},
            {'key': 'B', 'text': 'No overflow handling'},
            {'key': 'C', 'text': 'Text overlapping buttons'},
            {'key': 'D', 'text': 'Removing all constraints'},
        ],
        'correct_choice': 'A',
        'explanation': 'Stable constraints keep the UI polished as content grows.',
    },
    {
        'skill': 'design',
        'level': 'advanced',
        'prompt': 'A usability test shows users miss the primary action. What should you inspect first?',
        'choices': [
            {'key': 'A', 'text': 'Hierarchy, placement, label clarity, and contrast'},
            {'key': 'B', 'text': 'The server timezone only'},
            {'key': 'C', 'text': 'The package lock file only'},
            {'key': 'D', 'text': 'The image filename only'},
        ],
        'correct_choice': 'A',
        'explanation': 'Discoverability depends on hierarchy, placement, labels, and contrast.',
    },
    {
        'skill': 'design',
        'level': 'advanced',
        'prompt': 'What should happen visually after a user initiates payment or signing?',
        'choices': [
            {'key': 'A', 'text': 'Show clear progress, disabled duplicate actions, and next-step feedback'},
            {'key': 'B', 'text': 'Leave the button unchanged forever'},
            {'key': 'C', 'text': 'Hide all status information'},
            {'key': 'D', 'text': 'Navigate randomly'},
        ],
        'correct_choice': 'A',
        'explanation': 'Critical workflows need clear feedback and duplicate-action prevention.',
    },
    {
        'skill': 'writing',
        'level': 'beginner',
        'prompt': 'What is the purpose of a topic sentence?',
        'choices': [
            {'key': 'A', 'text': 'Introduce the main idea of a paragraph'},
            {'key': 'B', 'text': 'Hide the main idea'},
            {'key': 'C', 'text': 'Replace punctuation'},
            {'key': 'D', 'text': 'End the document only'},
        ],
        'correct_choice': 'A',
        'explanation': 'A topic sentence frames the paragraph for the reader.',
    },
    {
        'skill': 'writing',
        'level': 'beginner',
        'prompt': 'Which sentence is clearest for client communication?',
        'choices': [
            {'key': 'A', 'text': 'I will send the draft by Friday at 4 PM.'},
            {'key': 'B', 'text': 'Maybe soon stuff comes.'},
            {'key': 'C', 'text': 'Words are doing things.'},
            {'key': 'D', 'text': 'The deliverable perhaps eventually.'},
        ],
        'correct_choice': 'A',
        'explanation': 'Clear writing names the action, deliverable, and time.',
    },
    {
        'skill': 'writing',
        'level': 'beginner',
        'prompt': 'Why should proofreading happen before submission?',
        'choices': [
            {'key': 'A', 'text': 'To catch errors and improve professionalism'},
            {'key': 'B', 'text': 'To add random typos'},
            {'key': 'C', 'text': 'To remove all headings'},
            {'key': 'D', 'text': 'To hide the point'},
        ],
        'correct_choice': 'A',
        'explanation': 'Proofreading protects clarity and credibility.',
    },
    {
        'skill': 'writing',
        'level': 'beginner',
        'prompt': 'What does audience awareness mean?',
        'choices': [
            {'key': 'A', 'text': 'Writing for the needs and context of the reader'},
            {'key': 'B', 'text': 'Ignoring who will read it'},
            {'key': 'C', 'text': 'Using only jargon'},
            {'key': 'D', 'text': 'Never revising'},
        ],
        'correct_choice': 'A',
        'explanation': 'Good writing adapts to the reader and purpose.',
    },
    {
        'skill': 'writing',
        'level': 'beginner',
        'prompt': 'A proposal should usually show that the freelancer:',
        'choices': [
            {'key': 'A', 'text': 'Understands the client brief'},
            {'key': 'B', 'text': 'Copied a generic template only'},
            {'key': 'C', 'text': 'Did not read the project'},
            {'key': 'D', 'text': 'Cannot explain the approach'},
        ],
        'correct_choice': 'A',
        'explanation': 'Specific proposals build trust by responding to the actual brief.',
    },
    {
        'skill': 'writing',
        'level': 'intermediate',
        'prompt': 'Which revision most improves this sentence: "The project was done by me quickly"?',
        'choices': [
            {'key': 'A', 'text': 'I completed the project quickly.'},
            {'key': 'B', 'text': 'Quickly project me done.'},
            {'key': 'C', 'text': 'The done was project quickly.'},
            {'key': 'D', 'text': 'Me was done project.'},
        ],
        'correct_choice': 'A',
        'explanation': 'Active voice is clearer and more direct here.',
    },
    {
        'skill': 'writing',
        'level': 'intermediate',
        'prompt': 'What makes a case study stronger?',
        'choices': [
            {'key': 'A', 'text': 'Problem, approach, outcome, and evidence'},
            {'key': 'B', 'text': 'Only vague praise'},
            {'key': 'C', 'text': 'No structure'},
            {'key': 'D', 'text': 'Missing results'},
        ],
        'correct_choice': 'A',
        'explanation': 'A strong case study explains context, work, and measurable impact.',
    },
    {
        'skill': 'writing',
        'level': 'intermediate',
        'prompt': 'A client asks for a revision. What is the best first written response?',
        'choices': [
            {'key': 'A', 'text': 'Acknowledge the feedback, clarify specifics, and confirm next steps'},
            {'key': 'B', 'text': 'Ignore the message'},
            {'key': 'C', 'text': 'Argue without reading details'},
            {'key': 'D', 'text': 'Submit the same file again with no note'},
        ],
        'correct_choice': 'A',
        'explanation': 'Professional revision communication is specific and action-oriented.',
    },
    {
        'skill': 'writing',
        'level': 'intermediate',
        'prompt': 'What is the main purpose of transitions between paragraphs?',
        'choices': [
            {'key': 'A', 'text': 'Connect ideas smoothly'},
            {'key': 'B', 'text': 'Confuse readers'},
            {'key': 'C', 'text': 'Remove structure'},
            {'key': 'D', 'text': 'Replace sources'},
        ],
        'correct_choice': 'A',
        'explanation': 'Transitions help readers follow the logic.',
    },
    {
        'skill': 'writing',
        'level': 'intermediate',
        'prompt': 'Which is best when summarizing technical work for a non-technical client?',
        'choices': [
            {'key': 'A', 'text': 'Use plain language and focus on business impact'},
            {'key': 'B', 'text': 'Use unexplained jargon only'},
            {'key': 'C', 'text': 'Omit all outcomes'},
            {'key': 'D', 'text': 'Make it longer without purpose'},
        ],
        'correct_choice': 'A',
        'explanation': 'Client-facing summaries should translate work into clear value.',
    },
    {
        'skill': 'writing',
        'level': 'advanced',
        'prompt': 'What is the strongest way to handle weak evidence in analytical writing?',
        'choices': [
            {'key': 'A', 'text': 'Qualify the claim and identify what evidence is missing'},
            {'key': 'B', 'text': 'Pretend the evidence is conclusive'},
            {'key': 'C', 'text': 'Ignore sources'},
            {'key': 'D', 'text': 'Make the claim louder'},
        ],
        'correct_choice': 'A',
        'explanation': 'Advanced writing handles uncertainty honestly and precisely.',
    },
    {
        'skill': 'writing',
        'level': 'advanced',
        'prompt': 'A persuasive proposal should balance confidence with:',
        'choices': [
            {'key': 'A', 'text': 'Specific evidence and realistic scope'},
            {'key': 'B', 'text': 'Unsupported promises'},
            {'key': 'C', 'text': 'Hidden assumptions'},
            {'key': 'D', 'text': 'No timeline'},
        ],
        'correct_choice': 'A',
        'explanation': 'Persuasion is stronger when claims are backed and realistic.',
    },
    {
        'skill': 'writing',
        'level': 'advanced',
        'prompt': 'What is the best approach when editing for concision?',
        'choices': [
            {'key': 'A', 'text': 'Remove repetition and keep meaning intact'},
            {'key': 'B', 'text': 'Delete random sentences without checking logic'},
            {'key': 'C', 'text': 'Make every sentence vague'},
            {'key': 'D', 'text': 'Add filler phrases'},
        ],
        'correct_choice': 'A',
        'explanation': 'Concise editing preserves meaning while reducing unnecessary words.',
    },
    {
        'skill': 'writing',
        'level': 'advanced',
        'prompt': 'Why is tone control important in dispute communication?',
        'choices': [
            {'key': 'A', 'text': 'It keeps the exchange professional and evidence-focused'},
            {'key': 'B', 'text': 'It escalates conflict'},
            {'key': 'C', 'text': 'It removes facts'},
            {'key': 'D', 'text': 'It hides deadlines'},
        ],
        'correct_choice': 'A',
        'explanation': 'Professional tone helps disputes stay fair and resolvable.',
    },
    {
        'skill': 'writing',
        'level': 'advanced',
        'prompt': 'What makes instructions in a handoff document effective?',
        'choices': [
            {'key': 'A', 'text': 'Clear steps, context, dependencies, and expected outcomes'},
            {'key': 'B', 'text': 'Ambiguous references'},
            {'key': 'C', 'text': 'No order'},
            {'key': 'D', 'text': 'Missing assumptions'},
        ],
        'correct_choice': 'A',
        'explanation': 'Strong handoffs reduce confusion and rework.',
    },
]


class Command(BaseCommand):
    help = 'Seed approved Lexa skill assessment questions.'

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for item in QUESTIONS:
            _, was_created = SkillAssessmentQuestion.objects.update_or_create(
                skill=item['skill'],
                level=item['level'],
                prompt=item['prompt'],
                defaults={
                    'choices': item['choices'],
                    'correct_choice': item['correct_choice'],
                    'explanation': item['explanation'],
                    'is_active': True,
                }
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Seeded skill questions. Created: {created}, updated: {updated}.'
        ))
