# Generated by Django 4.2 on 2026-05-15 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proposal_competency_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestone_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_mode',
            field=models.CharField(choices=[('project_completion', 'Pay at Project Completion'), ('milestone', 'Pay by Milestone')], default='project_completion', max_length=24),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('released', 'Released')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.contract')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
