# Generated by Django 4.2 on 2026-05-23 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skillassessmentquestion_skillassessmentattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experience_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='preferred_background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='required_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ai_matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ai_most_relevant_role',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('skills_used', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('profile', 'Profile')], default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
