# Generated by Django 4.2 on 2026-05-15 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_milestone_plan_project_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('web_development', 'Web Development'), ('design', 'Design'), ('writing', 'Writing')], max_length=40)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_choice', models.CharField(max_length=5)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['skill', 'level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('web_development', 'Web Development'), ('design', 'Design'), ('writing', 'Writing')], max_length=40)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('question_ids', models.JSONField(default=list)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=12)),
                ('question_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('web_development', 'Web Development'), ('design', 'Design'), ('writing', 'Writing')], max_length=40)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('best_score', models.PositiveSmallIntegerField(default=0)),
                ('last_score', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill', 'level'],
                'unique_together': {('user', 'skill', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(blank=True, max_length=5)),
                ('is_correct', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.skillassessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skillassessmentquestion')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
